version: "3.7"
services:
    api:
        image: libraryapi
        ports:
            - "5000:80"
        environment: 
            - rabbit:HostName=rabbit
            - rabbit:UserName=guest
            - rabbit:Password=guest
            - rabbit:Port=5672
            - rabbit:VHost=/
            - redisHost=redis
            - ConnectionStrings__LibraryDatabase=server=sql;database=library;user id=SA;password=Tokyo!_Joe138
        networks:
            - my-network
    sql:
        image: librarysql
        ports: 
            - "1433:1433"
        networks:
            - my-network
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - my-network
    rabbit:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - my-network
networks:
    my-network:
        driver: bridge